### ISSUE TITLE
Anisotropic springs for crosslinks

### ISSUE THREAD

**Issue by jeffmm** [jeffmm/simcore#9]
**What is needed?**
Anisotropic springs for asymmetric compressive and stretched spring constants.

**Feature implementation**
Add optional second lookup table for each crosslink calculated with a second spring constant for compressed spring forces and check for anisotropic_spring_flag to implement asymmetric spring forces.

**Additional context**
Simcore currently throws warning when anisotropic spring flag is true to let user know that feature is unimplemented.

**Comment by jeffmm** [comment]
Is this feature currently available from your recent commits @lamsoa729 ?

**Comment by lamsoa729** [comment]
Not yet. I need to make the lut_filler subclass and add the necessary parameters. Maybe 30-60 min work without extensive testing. Urgency level?

**Comment by jeffmm** [comment]
Not at all, just checking because I remember you brought it up at a recent group meeting.

**Comment by jeffmm** [comment]
Addressed in PR #32
